# Generated by Django 5.0.6 on 2024-05-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
